version: '2'

services:
  node:
    container_name: thetime-node
    build: .
    ports:
      - "58888:58888"
    volumes:
      - ./package.json:/app/package.json
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
  mongodb:
    container_name: thetime-mongodb
    image: mongo