version: '2'

services:
  node:
    container_name: thetime-node
    build: .
    ports:
      - "58888:8888"
    networks:
      - thetime-network
    depends_on:
      - mongodb

  mongodb:
    container_name: thetime-mongodb
    image: mongo
    networks:
      - thetime-network

networks:
  thetime-network:
    driver: bridge